# Generated by Django 5.0.1 on 2024-01-18 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoandcontacts',
            name='logo',
            field=models.FileField(upload_to='images/logo/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Логотип'),
        ),
    ]
