# Generated by Django 5.0.1 on 2024-01-19 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0002_alter_logoandcontacts_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='images/soc_icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Иконка')),
                ('link', models.URLField(blank=True, max_length=100, verbose_name='Ссылка на аккаунт')),
                ('share', models.URLField(blank=True, max_length=100, verbose_name='Ссылка шеринга')),
                ('alt', models.CharField(blank=True, max_length=30, verbose_name='Alt инфо')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
        ),
    ]
