# Generated by Django 5.0.1 on 2024-01-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0003_soc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soc',
            name='share',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка шеринга'),
        ),
    ]
