# Generated by Django 5.0.1 on 2024-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0004_alter_soc_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slider_img/', verbose_name='Изображение')),
                ('header', models.CharField(blank=True, max_length=60, verbose_name='Заголовок слайдера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
