# Generated by Django 5.0.1 on 2024-01-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0007_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Почта'),
        ),
    ]
