# Generated by Django 5.0.1 on 2024-01-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider_app', '0008_mail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='email',
        ),
    ]
